# Delete these routes and define your own routes here
clictec_example_bundle_static_welcome:
    path: /static-welcome/{name}
    controller: Clictec\Bundle\ExampleBundle\Controller\TestController::staticallyGreetAction
    methods: GET
